package maps

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
)

// helper to capture stdout generated by a function
func captureOutput(f func()) string {
    var buf bytes.Buffer
    orig := os.Stdout
    r, w, _ := os.Pipe()
    os.Stdout = w
    f()
    w.Close()
    io.Copy(&buf, r)
    os.Stdout = orig
    return buf.String()
}

// create a minimal JSON payload with a given next url
func makePayload(next string) string {
    return fmt.Sprintf(`{"count":1,"next":"%s","previous":null,"results":[{"name":"foo","url":"/foo"}]}`,
        next)
}

func TestMapPagination(t *testing.T) {
    calls := 0
    var ts *httptest.Server
    ts = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        calls++
        switch calls {
        case 1:
            fmt.Fprintln(w, makePayload(ts.URL+"/page2"))
        case 2:
            fmt.Fprintln(w, makePayload(""))
        default:
            fmt.Fprintln(w, makePayload(ts.URL+"/page2"))
        }
    }))
    defer ts.Close()

    baseURL = ts.URL + "/page1"
    Reset()
    if interactionManager.InteractionCount != 0 {
        t.Fatalf("reset left interactions: %d", interactionManager.InteractionCount)
    }

    out := captureOutput(func() {
        if err := Map(); err != nil {
            t.Fatalf("first call failed: %v", err)
        }
    })
    if currentURL != ts.URL+"/page2" {
        t.Errorf("expected currentURL to be next page, got %q", currentURL)
    }
    if interactionManager.InteractionCount != 1 {
        t.Errorf("expected 1 interaction recorded, got %d", interactionManager.InteractionCount)
    }
    if interactionManager.Interactions[1].Next != ts.URL+"/page2" {
        t.Errorf("recorded next URL incorrect: %q", interactionManager.Interactions[1].Next)
    }
    if !strings.Contains(strings.TrimSpace(out), "foo") {
        t.Errorf("output missing name: %s", out)
    }

    if err := Map(); err != nil {
        t.Fatalf("second call failed: %v", err)
    }
    if currentURL != "" {
        t.Errorf("expected currentURL to reset after reaching end, got %q", currentURL)
    }
    if interactionManager.InteractionCount != 2 {
        t.Errorf("expected 2 interactions recorded, got %d", interactionManager.InteractionCount)
    }
    if interactionManager.Interactions[2].Next != "" {
        t.Errorf("second recorded next URL incorrect: %q", interactionManager.Interactions[2].Next)
    }

    if err := Map(); err != nil {
        t.Fatalf("third call failed: %v", err)
    }
    if currentURL != ts.URL+"/page2" {
        t.Errorf("after resetting, expected to fetch baseURL and then next, got %q", currentURL)
    }
    if interactionManager.InteractionCount != 3 {
        t.Errorf("expected 3 interactions recorded, got %d", interactionManager.InteractionCount)
    }
}
