package maps

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
)

// helper to capture stdout generated by a function (distinct from the
// version used by map_test.go to avoid redeclaration).
func captureOutputB(f func()) string {
    var buf bytes.Buffer
    orig := os.Stdout
    r, w, _ := os.Pipe()
    os.Stdout = w
    f()
    w.Close()
    io.Copy(&buf, r)
    os.Stdout = orig
    return buf.String()
}

// minimal payload containing a previous link and a single result name
func makePayloadB(prev string) string {
    return fmt.Sprintf(
        `{"count":1,"next":"","previous":"%s","results":[{"name":"bar","url":"/bar"}]}`,
        prev)
}

func TestMapBUsesPrevious(t *testing.T) {
    calls := 0
    var ts *httptest.Server
    ts = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        calls++
        switch calls {
        case 1:
            // first call returns a previous link so mapb can walk backward
            fmt.Fprintln(w, makePayloadB(ts.URL+"/page1"))
        case 2:
            // second call returns no previous
            fmt.Fprintln(w, makePayloadB(""))
        default:
            fmt.Fprintln(w, makePayloadB(""))
        }
    }))
    defer ts.Close()

    baseURLB = ts.URL + "/page2"
    ResetB()
    resetRequestCache()

    out := captureOutputB(func() {
        if err := MapB(); err != nil {
            t.Fatalf("first call failed: %v", err)
        }
    })
    // the first invocation should fall back to baseURLB and therefore
    // include our decorative beginning message.
    if !strings.Contains(out, "*** REACHED BEGINNING ***") {
        t.Errorf("missing beginning log: %s", out)
    }
    if !strings.Contains(strings.TrimSpace(out), "bar") {
        t.Errorf("output missing name: %s", out)
    }
    if !strings.Contains(out, "*** PAGE COMPLETE ***") {
        t.Errorf("missing completion flair: %s", out)
    }
    // currentURL should now record the URL we just fetched (base page)
    if currentURL != ts.URL+"/page2" {
        t.Errorf("expected currentURL to be base page after first call, got %q", currentURL)
    }

    // clear cache so the second request hits the server again
    resetRequestCache()

    out2 := captureOutputB(func() {
        if err := MapB(); err != nil {
            t.Fatalf("second call failed: %v", err)
        }
    })
    // since the previous value from the *first* payload pointed to page1, the
    // second call should follow that link rather than print the beginning
    // message.  (The empty previous in the second payload will only be seen
    // on the *next* invocation.)
    if strings.Contains(out2, "*** REACHED BEGINNING ***") {
        t.Errorf("unexpected beginning log on second call: %s", out2)
    }
    if currentURL != ts.URL+"/page1" {
        t.Errorf("expected currentURL=%q, got %q", ts.URL+"/page1", currentURL)
    }

    // perform a third call; now currentLocations.Previous is empty, so we
    // should see the fallback log and hit baseURLB again.
    resetRequestCache()
    out3 := captureOutputB(func() {
        if err := MapB(); err != nil {
            t.Fatalf("third call failed: %v", err)
        }
    })
    if !strings.Contains(out3, "*** REACHED BEGINNING ***") {
        t.Errorf("expected beginning log on third call: %s", out3)
    }
    if !strings.Contains(out3, "*** PAGE COMPLETE ***") {
        t.Errorf("missing completion flair on third call: %s", out3)
    }
    if currentURL != ts.URL+"/page2" {
        t.Errorf("expected currentURL back at base, got %q", currentURL)
    }
}
