package maps

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
)

// helper to capture stdout generated by a function (distinct from the
// version used by map_test.go to avoid redeclaration).
func captureOutputB(f func()) string {
    var buf bytes.Buffer
    orig := os.Stdout
    r, w, _ := os.Pipe()
    os.Stdout = w
    f()
    w.Close()
    io.Copy(&buf, r)
    os.Stdout = orig
    return buf.String()
}

// minimal payload containing a previous link and a single result name
func makePayloadB(prev string) string {
    return fmt.Sprintf(
        `{"count":1,"next":"","previous":"%s","results":[{"name":"bar","url":"/bar"}]}`,
        prev)
}

func TestMapBUsesPrevious(t *testing.T) {
    calls := 0
    var ts *httptest.Server
    ts = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        calls++
        switch calls {
        case 1:
            fmt.Fprintln(w, makePayloadB(""))
        case 2:
            fmt.Fprintln(w, makePayloadB(ts.URL+"/page1"))
        default:
            fmt.Fprintln(w, makePayloadB(""))
        }
    }))
    defer ts.Close()

    baseURLB = ts.URL + "/page2"
    ResetB()

    out := captureOutputB(func() {
        if err := MapB(); err != nil {
            t.Fatalf("first call failed: %v", err)
        }
    })
    if !strings.Contains(strings.TrimSpace(out), "bar") {
        t.Errorf("output missing name: %s", out)
    }
    if currentURLB != "" {
        t.Errorf("expected currentURLB empty after first call, got %q", currentURLB)
    }

    if err := MapB(); err != nil {
        t.Fatalf("second call failed: %v", err)
    }
    if currentURLB != ts.URL+"/page1" {
        t.Errorf("expected currentURLB=%q, got %q", ts.URL+"/page1", currentURLB)
    }
}
